services/line-stat-getter.js, services/pie-stat-getter.js
=> ES5 - Fix remaining ES5 incompatible syntax

CHANGELOG.md, adapters/mongoose.js
Fixes https://github.com/ForestAdmin/forest-express-mongoose/issues/44
=> [+] Enums - Support Enums in subdocuments

CHANGELOG.md, package.json
⚠️ Wait for this PR ForestAdmin/forest-express#70 merge before approval ⚠️
=> [+] Setup Guide - Add integration field to the collections to distinguish Smart Collections and Collections from integrations

CHANGELOG.md, package.json
⚠️ Wait for the following PR ForestAdmin/forest-express#73 to merge ⚠️
=> [+] Smart Fields - Developers can now define Smart Fields setters

CHANGELOG.md, services/resource-updater.js
Fixes: https://github.com/ForestAdmin/forest-express-mongoose/issues/57
=> [*] Record Update - Trigger validations on record update

CHANGELOG.md, package.json
Wait for this PR to be merged: https://github.com/ForestAdmin/forest-express/pull/83
=> [*] HasMany Smart Fields - Fix routes conflicts between hasMany Smart Fields and other associations

CHANGELOG.md, services/resources-getter.js
=> [*]  Search - Fix crash on hasmany array association.

CHANGELOG.md, index.js
=> [+] Technical - Send mongoose version in apimap.

CHANGELOG.md, index.js
=> [*] Liana Version & Orm Version - Prevent server crash on bad format version.

CHANGELOG.md, services/operator-value-parser.js
=> [+] Filters - Add the before x hours operator.

.eslintrc.js, CHANGELOG.md, package.json, services/handle-search.js, services/has-many-getter.js, services/resources-getter.js, services/search-builder.js
=> [+] Search - Users can search on the hasMany associated data of a specific record

CHANGELOG.md, index.js, package.json, services/records-exporter.js
=> [+] Exports - Forest can now handle large data exports

CHANGELOG.md, services/search-builder.js
=> [+] Search - Search on embedded arrays with deep parameter.

CHANGELOG.md, package.json
=> [*] Exports - Fix bad initial implementation for exports authentication

CHANGELOG.md, index.js
=> [+] Integrations - Add the Layer integration

CHANGELOG.md, adapters/mongoose.js
=> [-] Models Introspection - Support nested custom schemas for models

CHANGELOG.md, adapters/mongoose.js, services/resources-getter.js, services/search-builder.js
=> [+] Search - Developers can configure in which fields the search will be executed.

.npmrc, CHANGELOG.md, package.json
=> [-] Security - Remove all detected vulnerabilities upgrading some dependencies

CHANGELOG.md, adapters/mongoose.js, index.js, package.json, test/mongoose.js, utils/schema.js, yarn.lock
=> [-] Collections Names - Collection names are now based on the model name

CHANGELOG.md, adapters/mongoose.js, index.js, services/line-stat-getter.js, services/mongoose-utils.js, services/pie-stat-getter.js, test/mongoose.js, utils/schema.js
Here is an example to test this feature:
```javascript
var connection = mongoose.createConnection('mongodb://localhost/tanks');
var schema = mongoose.Schema({ name: 'string', size: 'string' });
var Tank = connection.model('Tank', schema);
app.use(require('forest-express-mongoose').init({
modelsDir: null, //__dirname + '/models',
envSecret: process.env.FOREST_ENV_SECRET,
authSecret: process.env.FOREST_AUTH_SECRET,
connections: [connection],
mongoose: require('mongoose')
}));
```
=> [+] Databases Connections - Support multiple mongoose connections

CHANGELOG.md, services/operator-value-parser.js
=> [+] Filters - Add a new "is after X hours ago" operator to filter on date fields

CHANGELOG.md, services/has-many-associator.js, services/has-many-dissociator.js
=> [+] Related Data - Delete records directly from a hasMany listing

CHANGELOG.md, package.json, yarn.lock
=> [*] Premium Security - Handle mutli instances ip whitelist refresh

CHANGELOG.md, package.json, yarn.lock
=> [-] Technical - Save exact dependencies version

CHANGELOG.md, index.js, package.json, services/has-many-getter.js, services/records-exporter.js, services/resources-getter.js, services/search-builder.js, test/tests/services/resources-getter.js, utils/records-decorator.js, yarn.lock
=> [+] Search - Display highlighted matches on table view when searching

CHANGELOG.md, index.js
=> [+] Mixpanel Integration - Add an integration to display the last Mixpanel events

CHANGELOG.md, package.json, services/has-many-getter.js, services/resources-getter.js, test/tests/services/resources-getter.js, test/utils/mongoose-connect.js, yarn.lock
=> [-] Performance - Improve the speed of listing the records by executing their count into another request

CHANGELOG.md, adapters/mongoose.js, package.json, test/tests/adapters/expected-results/deep-nested-object.json, test/tests/adapters/expected-results/deep-nested-schema.json, test/tests/adapters/expected-results/real-world-schema.json, test/tests/adapters/mongoose.js, test/tests/adapters/schemas/complex-shema.js, yarn.lock
=> [*] Mongoose - Handle last versions of mongoose by fixing the RangeOverflow error

.eslint-bin/js-list.json, CHANGELOG.md, src/services/filter-parser.js, src/services/line-stat-getter.js, src/services/operator-value-parser.js, src/services/pie-stat-getter.js, src/services/resources-getter.js, src/services/value-stat-getter.js
=> [-] Linter - Fix linter issues on chart stat getters

CHANGELOG.md, docker-compose.yml, package.json, src/index.js, src/services/line-stat-getter.js, src/services/pie-stat-getter.js, src/services/query-builder.js, src/services/query-params-to-orm-params.js, src/services/resources-getter.js, src/services/search-builder.js, src/services/value-stat-getter.js, src/utils/orm.js, src/utils/records-decorator.js, test/tests/services/resources-getter.js
=> [*] Filter - Fix or filter when filtering on a belongsTo with another simple attribute

CHANGELOG.md, src/services/query-builder.js
=> [*] Records list - Add defensive programming against unexpected internal error on resources display

CHANGELOG.md, src/services/query-builder.js, test/tests/services/query-builder.js
=> [*] Query Builder - Fix broken queries on collection having integrations

CHANGELOG.md, src/services/query-builder.js, test/tests/services/query-builder.js
=> [*] Query Builder - Fix broken queries on virtual smart relationships

CHANGELOG.md, src/services/query-builder.js, test/tests/services/query-builder.js
=> [*] Query Builder - Fix again broken queries on collection having integrations [Regression introduced in 4.0.5]

.npmignore, CHANGELOG.md
=> [*] NPM Publish - Do not send local environment variables on package publish

CHANGELOG.md, src/services/has-many-getter.js, src/services/line-stat-getter.js, src/services/pie-stat-getter.js, src/services/query-builder.js, src/services/resources-getter.js, src/services/search-builder.js, src/services/value-stat-getter.js, test/tests/services/query-builder.js
=> [*] Records Lists - Improve performance (Regression introduced on v4.0.0)

CHANGELOG.md, src/index.js, src/services/resources-exporter.js
=> [*] Technical - Clean the ResourcesExporter service

package.json, src/services/filters-parser.js, src/services/query-builder.js, src/services/resources-getter.js, test/tests/services/filters-parser.js, test/tests/services/resources-getter.js, yarn.lock
- https://github.com/ForestAdmin/forest-express/pull/274
=> [*] Records List - Improve performance when filtering on belongs to

CHANGELOG.md, package.json, yarn.lock
See: https://github.com/ForestAdmin/forest-express/commit/b9ab46c73f5468f0a0336c58480e10f688fcbd9c
=> [-] Technical - Upgrade to the `forest-express` v5.1.1

CHANGELOG.md, package.json, src/index.js, src/services/resources-exporter.js, yarn.lock
This PR requires: https://github.com/ForestAdmin/forest-express/pull/278
And can be tested with: https://github.com/ForestAdmin/lumber/pull/324
=> [+] Routes - Expose the record services and the permissions middleware

.eslint-bin/pre-commit-hook.js, CHANGELOG.md
This PR exclude from pre-commit-hook linter files that will not be commited. This includes deleted files, untracked or not staged for commit changed files.
=> [*] Technical - Fix linted deleted files issue

CHANGELOG.md, src/services/filters-parser.js
=> [*] Technical - Refactorize `filters-parser`

CHANGELOG.md, src/services/filters-parser.js
=> [*] Record List - Fix record listing on table which reference table with id not string

CHANGELOG.md, package.json, src/services/line-stat-getter.js, test/tests/services/query-builder.test.js, test/tests/services/resources-getter.test.js, yarn.lock
=> [-] Technical - Use true timezone data ('Europe/Paris') instead of offset.

CHANGELOG.md, src/services/filters-parser.js, test/tests/services/filters-parser.test.js
=> [*] Record List - Fix filter is blank to also take into account null value

CHANGELOG.md, src/index.js, src/services/errors.js, src/services/resources-remover.js, test/tests/services/resources-remover.test.js
This PR adds a new `RecordsRemover` that handles bulk destroy.
Required by: https://github.com/ForestAdmin/forest-express/pull/346
=> [+] Resources Remover - Add resources remover (bulk destroy)

CHANGELOG.md, package.json, yarn.lock
- This PR uses the branch that will be used to release v6.0 beta.
- The changelog contains the two main changes made on `forest-express`.
- When merged, this should trigger a new breaking change version (i.e: v6)
=> [-] Technical - Update `forest-express` to version 7

CHANGELOG.md
This is required before I npm publish this Liana
=> [*] Technical - Fix changelog

CHANGELOG.md, package.json, yarn.lock
=> [*] Integrations - Fix intercom conversations display with API v2

CHANGELOG.md, package.json, yarn.lock
=> feat(integration): allow user to choose custom mapping values for intercom integration

.travis.yml, CHANGELOG.md, package.json, yarn.lock
=> ci: make the ci lint the commit messages

CHANGELOG.md
=> fix(changelog): remove release 6.0.2 from changelog

CHANGELOG.md, package.json, yarn.lock
=> chore(technical): adapt release manager to conventional commits

CHANGELOG.md, package.json, yarn.lock
=> chore(forest-express): upgrade forest-express dependency to 7.2.0

package.json, yarn.lock
=> fix(dependencies): update babel to fix compilation error introduced by node lts 12.17.0

package.json, yarn.lock
=> feat(forest-express): upgrade forest-express to 7.3.0 to add the scope validation feature

package.json, src/index.js, yarn.lock
=> fix(services): create and expose records remover

src/services/filters-parser.js, test/tests/services/filters-parser.test.js, test/tests/services/resources-getter.test.js
=> feat(filter): is blank now also filter empty strings

test/tests/services/resources-creator.test.js
Highly inspired by https://github.com/ForestAdmin/forest-express-mongoose/pull/373/files#diff-99a8cc4b878ca4d8ca8ca95198e5292a 😄
=> test: add resources-creator tests

test/tests/services/resource-remover.test.js
=> test: add test on resource-remover

src/services/resource-updater.js, test/tests/services/resources-updater.test.js
Linked to https://app.clickup.com/t/4rnzbx
=> fix: fix validator error on update

src/adapters/mongoose.js, test/tests/adapters/expected-results/deep-nested-schema.json, test/tests/adapters/mongoose.test.js
=> fix(adapter): avoid serializing enum function on Number type

package.json, yarn.lock
Fixes a lodash vulnerability imported through forest-express
Clickup card: https://app.clickup.com/t/6up7hd
=> fix(vulnerability): patch potential vulnerabilities updating forest-express to version 7.4.1

package.json, yarn.lock
=> fix(related data): fix related data display regression introduced in v6.3.4

package.json, yarn.lock
=> fix: prevent scopes validation crashes for conditions with boolean or number values

src/services/resource-remover.js, test/tests/services/filters-parser.test.js, test/tests/services/query-builder.test.js, test/tests/services/resource-remover.test.js, test/tests/services/resources-getter.test.js, test/tests/services/resources-remover.test.js
Removes call to mongoose deprecated functions
Based on the PR #393 (do not merge without merging the previous PR)
=> refactor: :recycle: remove calls to deprecated functions

test/tests/adapters/mongoose.test.js, test/tests/services/filters-parser.test.js, test/tests/services/query-builder.test.js, test/tests/services/resource-remover.test.js, test/tests/services/resources-creator.test.js, test/tests/services/resources-getter.test.js, test/tests/services/resources-remover.test.js, test/tests/services/resources-updater.test.js
=> improvement: :recycle: fix the usage of the keyword new in tests

package.json, yarn.lock
Shows auto-completion in the IDE when writing tests, and helps to find bugs
=> chore: show auto-completion in the IDE when writing tests

src/services/resources-getter.js, test/tests/services/resources-getter.test.js
=> fix: :bug: correctly return documents when filtering on a field that is not returned

src/services/has-many-dissociator.js, test/tests/services/has-many-dissociator.test.js
=> fix(has-many-dissociator): dissociate relationship when related record is deleted

package.json, yarn.lock
See: ForestAdmin/forest-express#535
=> feat(smart actions): add hooks in schema file

package.json
=> chore: improve build watch command to build cascade forest-express

.travis.yml
=> chore(ci): enable beta distribution channel for semantic-release

package.json, yarn.lock
=> chore(security): patch semantic release vulnerability

yarn.lock
=> chore(security): patch node-fetch vulnerability

package.json, yarn.lock
=> chore(forest-express): upgrade forest-express dependency to 7.7.2

test/tests/adapters/mongoose.test.js, test/tests/services/filters-parser.test.js, test/tests/services/query-builder.test.js, test/tests/services/resources-getter.test.js
=> chore: fix test connections option

package.json, yarn.lock
=> fix(smart fields): compute properly smart fields with mongoose

package.json, yarn.lock
=> feat(smart-actions): endpoint that handle forms' load hooks by upgrading forest-express version 

package.json, yarn.lock
=> feat(smart actions): introduce smart action forms hooks

package.json, yarn.lock
=> fix: array display with smart field

package.json, yarn.lock
=> fix: fix related data list display

package.json, yarn.lock
=> fix: display correct reference field when it is a smartfield

package.json, yarn.lock
=> fix: user being disconnected after 33min instead of 14 days

package.json, yarn.lock
=> fix(authentication): error when authenticating with an invalid token in cookies

jest.config.js, package.json, src/services/filters-parser.js, test/tests/services/filters-parser.test.js, yarn.lock
=> feat(filter): add possibility to filter on smart field

package.json, yarn.lock
=> fix(forestadmin-schema): regenerate forestadmin schema only when files are valid

.travis.yml
=> ci: add docker-hub login step in CI

package.json, yarn.lock
=> fix(smart-action-hook): value injected to an enum field of type  is now correctly handled

commitlint.config.js
=> ci: consider all linting errors about line length as warnings

package.json, yarn.lock
=> chore: bump forest-express version to 8.0.0-beta.13

README.md
=> docs(readme): fix the CI status badge

.github/workflows/build.yml
=> refactor(ci): simplify CI configuration

package.json, yarn.lock
=> chore: use the released version of forest-express

.github/workflows/build.yml, README.md
=> chore: merge master into beta

CHANGELOG.md
=> docs(force-release): update the changelog about the version 7.0.0, force the release of a 7.0.1

package.json, yarn.lock
=> fix(authentication): safari cannot login on remote lianas because of third party cookies

package.json, yarn.lock
=> fix(security): patch lodash vulnerabilities

package.json, yarn.lock
=> feat(security): authorised only allowed stats queries using permissions

package.json, yarn.lock
=> fix(security): downgrade forest-express while the charts are broken

package.json, yarn.lock
=> fix(security): authorised only allowed stats queries using permissions

src/services/has-many-getter.js, test/tests/services/has-many-getter.test.js
=> feat: add filters on related data

yarn.lock
=> fix(security): patch npm-user-validate dependency vulnerabilities

package.json, yarn.lock
=> fix(security): patch forest-express transitive vulnerabilities

yarn.lock
=> fix(security): patch node-fetch dependency vulnerability

package.json, yarn.lock
=> fix(security): patch mquery dependency vulnerabilities

package.json, yarn.lock
=> feat(smart-action): support hooks for smart collection

package.json, yarn.lock
=> feat(smart-action): handle isReadOnly field in smart action forms

package.json, yarn.lock
=> fix(date-filter): filtering only on hours now returns the expected records

package.json, yarn.lock
=> feat: support yarn 2 plug n play install mode

yarn.lock
=> refactor: deprecation warning on `caniuse-lite` (console flood)

src/services/resource-remover.js, test/tests/services/filters-parser.test.js, test/tests/services/has-many-dissociator.test.js, test/tests/services/has-many-getter.test.js, test/tests/services/query-builder.test.js, test/tests/services/resource-remover.test.js, test/tests/services/resources-getter.test.js, test/tests/services/resources-remover.test.js
=> refactor: deprecation warning on `model.remove()` (console flood)

package.json, yarn.lock
=> build: stop watching forest-express to rebuild

test/tests/services/has-many-dissociator.test.js
=> test: race condition makes test fail randomly

test/utils/mongoose-connect.js
=> refactor: deprecation warning on `model.findAndModify()` (console flood)

src/adapters/mongoose.js, src/services/belongs-to-updater.js, src/services/filters-parser.js, src/services/has-many-associator.js, src/services/has-many-dissociator.js, src/services/has-many-getter.js, src/services/line-stat-getter.js, src/services/pie-stat-getter.js, src/services/query-builder.js, src/services/resource-creator.js, src/services/resource-getter.js, src/services/resource-remover.js, src/services/resource-updater.js, src/services/resources-exporter.js, src/services/resources-getter.js, src/services/search-builder.js, src/services/value-stat-getter.js, test/tests/services/filters-parser.test.js, test/tests/services/has-many-dissociator.test.js, test/tests/services/has-many-getter.test.js, test/tests/services/line-stat-getter.test.js, test/tests/services/pie-stat-getter.test.js, test/tests/services/query-builder.test.js, test/tests/services/resource-remover.test.js, test/tests/services/resources-getter.test.js, test/tests/services/resources-remover.test.js, test/tests/services/resources-updater.test.js, test/tests/services/value-stat-getter.test.js, test/utils/mongoose-connect.js
When reviewing, ignore white spaces.
=> refactor: migrate project to async/await syntax

package.json, yarn.lock
=> fix: distribution charts using groupby on a relationship throws 403 Forbidden

package.json, yarn.lock
=> fix(smart-actions-change-hook): record is no longer altered and is sent correctly

src/services/has-many-getter.js, src/services/line-stat-getter.js, src/services/pie-stat-getter.js, src/services/resource-creator.js, src/services/resource-getter.js, src/services/resource-remover.js, src/services/resource-updater.js, src/services/resources-exporter.js, src/services/resources-getter.js, src/services/resources-remover.js, src/services/value-stat-getter.js, src/utils/scopes.js, test/tests/services/has-many-getter.test.js, test/tests/services/line-stat-getter.test.js, test/tests/services/pie-stat-getter.test.js, test/tests/services/resource-getter.test.js, test/tests/services/resource-remover.test.js, test/tests/services/resources-creator.test.js, test/tests/services/resources-getter.test.js, test/tests/services/resources-remover.test.js, test/tests/services/resources-updater.test.js, test/tests/services/value-stat-getter.test.js
=> feat: check scopes on services

package.json, src/services/has-many-getter.js, src/services/line-stat-getter.js, src/services/pie-stat-getter.js, src/services/resource-creator.js, src/services/resource-getter.js, src/services/resource-remover.js, src/services/resource-updater.js, src/services/resources-exporter.js, src/services/resources-getter.js, src/services/resources-remover.js, src/services/value-stat-getter.js, src/utils/scopes.js, test/tests/services/has-many-getter.test.js, test/tests/services/line-stat-getter.test.js, test/tests/services/pie-stat-getter.test.js, test/tests/services/resource-getter.test.js, test/tests/services/resource-remover.test.js, test/tests/services/resources-creator.test.js, test/tests/services/resources-getter.test.js, test/tests/services/resources-remover.test.js, test/tests/services/resources-updater.test.js, test/tests/services/value-stat-getter.test.js, yarn.lock
=> feat(scopes): enforce scopes restrictions on a wider range of requests

package.json, yarn.lock
=> feat(schema): move some meta data under stack attribute to prevent blocking scenarios on DWO

package.json, yarn.lock
=> fix: correctly get the IP address from the request headers

README.md
=> docs(readme): fix alt text in README

package.json, yarn.lock
=> feat: include role in the user data inside the request

package.json, yarn.lock
=> fix: prevent IP check from failing for the proxies including the port in the headers

package.json, yarn.lock
=> fix(intercom): fix date conversion from unix timestamp to js date of intercom attributes

src/services/value-stat-getter.js
=> fix: broken value charts due to missing user on ValueStatGetter constructor

package.json, yarn.lock
=> fix(authentication): error during authentication when the environment is secret passed as a liana option and not an environment variable

package.json, yarn.lock
=> fix(related-data): reaching an embedded has-many relationship by URL does not display any records on mongoose

src/adapters/mongoose.js, test/tests/adapters/expected-results/deep-nested-schema.json, test/tests/adapters/mongoose.test.js
=> fix(enums): fix nested enum types not having values in forestadmin-schema

.github/PULL_REQUEST_TEMPLATE.md, package.json, types/.eslintrc.js, types/index.d.ts, yarn.lock
The is the first attempt of adding Types definition in our repo directly.
Observations
The how to translate your app into typescript page on the Woodshop is, by far, the second most consulted page.
Some of our top paying clients using mongoose develops using Typescript
We recently have been addressed some issues regarding our Types definition in the community (see this card for more info)
Maintaining Types in DefinitelyTyped has been done using a community approach till now. This leads to some frustration when users upgrade their lianas without updates on their types. Some of our dependencies also have stoped working DefinitelyTyped and integrate their own Types directly in their repos, which makes hard if not impossible to synchronise our own Types. Maintaining Types DefinitelyTyped also …
=> feat: add typescript declaration file

package.json, yarn.lock
=> feat(security): secure segments queries

types/.eslintrc.js
=> chore: enforce array syntax for types

types/index.d.ts
=> fix: add missing json value for fieldtype type

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/build.yml, CHANGELOG.md, README.md, package.json, src/adapters/mongoose.js, test/tests/adapters/expected-results/deep-nested-schema.json, test/tests/adapters/mongoose.test.js, types/.eslintrc.js, types/index.d.ts, yarn.lock
=> chore: merge master into beta + typing

types/index.d.ts
=> fix: add isSearchable to collection options

types/index.d.ts
=> fix: abstractRecord type

package.json, yarn.lock
=> chore: add express type dependency

package.json, types/index.d.ts, yarn.lock
=> feat: allow hooks for global and bulk smart action

package.json, yarn.lock
=> chore(force-release): update forest-express to V9

src/index.js, src/services/fields-flattener.js, test/tests/services/fields-flattener.test.js, types/index.d.ts
Types have already been updated here --> https://github.com/ForestAdmin/forest-express-mongoose/pull/619/files
=> feat(mongoose-nested-fields): generate flattened fields in schema

package.json, yarn.lock
=> fix(update): fix update record regression

src/services/fields-flattener.js, src/services/filters-parser.js, test/tests/services/fields-flattener.test.js, test/tests/services/filters-parser.test.js
=> feat(flatten): flattened fields are now usable in scopes

src/index.js, src/middlewares/request-unflattener.js, src/services/query-builder.js, test/tests/middlewares/request-unflattener.test.js, test/tests/services/query-builder.test.js
=> feat(nested-fields-mongoose): add a way to unflatten data in the request

test/tests/services/flattener.test.js
=> fix: unflatten field name in the context

types/index.d.ts
=> chore: update typings from flatten to fieldsToFlatten

package.json, yarn.lock
=> chore: upgrade forest-express dependency

types/index.d.ts
=> fix(types): add missing RecordSerializer

package.json, types/index.d.ts, yarn.lock
=> fix(exposed): reduce number of mandatory parameters in records-getter and record-serializer

package.json, yarn.lock
=> fix(charts): objective charts now returns correct values

src/services/filters-parser.js, test/tests/services/filters-parser.test.js
=> feat(filter): add "is in" filter

yarn.lock
=> fix(security): patch glob-parent vulnerabilities

package.json, yarn.lock
Upgrade to the latest Babel versions to get rid of vulnerabilities detected by yarn audit and/or GitHub
=> fix(security): patch babel vulnerabilities

package.json, yarn.lock
`mongoose` minor version upgrade to upgrade the `mpath` dependencies and patch its vulnerability
=> fix(security): patch mpath dependency vulnerability

package.json, src/services/filters-parser.js, test/tests/services/filters-parser.test.js, yarn.lock
=> fix(smart field): fix filter on smart reference

types/index.d.ts
=> docs(force-release): add searchFields type in the collection options

src/services/flattener.js, src/services/query-builder.js, test/tests/services/flattener.test.js, test/tests/services/query-builder.test.js
=> fix(fields-flattener): flattened nested references are now correctly populated

package.json, src/services/flattener.js, src/services/resources-exporter.js, test/tests/services/flattener.test.js, yarn.lock
=> fix(export): flattened fields are now correctly exported

src/services/flattener.js, test/tests/services/flattener.test.js
=> fix: flattened array attributes are now correctly exported

package.json, yarn.lock
=> chore: deprecate old versions without errors when releasing the package

src/index.js, test/tests/index.test.js, types/index.d.ts
=> feat: export the request unflattener

src/services/flattener.js, test/tests/services/flattener.test.js
=> fix(flattener): fields null assignment is now properly handled

src/services/search-builder.js, test/tests/services/search-builder.test.js
=> fix(search): search extended on collection with array of numbers

types/index.d.ts
=> fix(types): serializers now take optional meta as second argument

package.json, yarn.lock
=> chore: update forest-express version

package.json, yarn.lock
=> fix: prevent deactivate count middleware to throw

package.json, yarn.lock
=> chore(force-release): bump forest-express from 9.4.1 t 9.4.2

package.json, yarn.lock
=> chore(force-release): bump forest-express from 9.4.3 to 9.4.6

package.json, yarn.lock
=> fix(security): patch express-jwt to latest stable candidate

package.json, src/services/flattener.js, src/utils/schema.js, test/tests/services/flattener.test.js, test/tests/utils/schema.test.js, yarn.lock
⚠️ This pr needs this one first : [update the way flattener is called in forest-express](https://github.com/ForestAdmin/forest-express/pull/882 ) ⚠️ 
[Clickup task](https://app.clickup.com/t/283apge)
[Story](https://forest.slite.com/app/docs/h1B5pyAgdPnBZ3#6f221fdf)
=> feat(flattener): native flattened fields are now entirely introspected

types/index.d.ts
=> fix(types): load and change hook are now optional on smart action

src/services/query-builder.js, test/tests/services/resources-getter.test.js
=> fix(reference): fix join of references when model name is different from table name

package.json, yarn.lock
=> fix(security): upgrade moment to 2.29.4 to fix a vulnerability

package.json, yarn.lock
=> fix(flattener): smart action availability now works properly on segments

package.json, yarn.lock
=> fix(charts): user with permissions level that allows charts creation or edition should always be allow to perform charts requests

.github/workflows/build.yml, .releaserc.js
=> chore: allow to release fixes on v7

.releaserc.js
=> chore: correctly release beta and support versions

types/index.d.ts
=> fix(type): add "isSortable" to SmartFieldOptions interface

package.json, yarn.lock
=> fix(has many): fix link of has many

package.json, yarn.lock
=> fix(security): validate that smart action approvals are launched with the same parameters than the initial trigger

src/services/value-stat-getter.js, test/tests/services/value-stat-getter.test.js
=> feat(chart): add support for objective chart

package.json, src/services/line-stat-getter.js, src/services/pie-stat-getter.js, src/services/value-stat-getter.js, src/utils/scopes.js, test/tests/services/line-stat-getter.test.js, test/tests/services/pie-stat-getter.test.js, test/tests/services/value-stat-getter.test.js, yarn.lock
=> fix(chart): improve security on chart and rename charts' properties

package.json, src/services/filters-parser.js, test/tests/services/filters-parser.test.js, yarn.lock
=> feat(chart): add support for context variables used by Workspaces

package.json, yarn.lock
=> chore: upgrade forest-express to 10.0.0

types/index.d.ts
=> fix(types): remove unused and incorrect exported type related to aggregation

types/index.d.ts
=> fix(types): smart field filter can now also returns a promise

types/index.d.ts
=> fix(types): add FilterOperator enum

package.json, yarn.lock
=> fix: add attribute reverse list word by upgrading forest-express

package.json, yarn.lock
=> chore(force-release): update the forest-express dependency to fix qs vulnerability

types/index.d.ts
=> fix(typing): remove invalid enum from typing file

package.json, yarn.lock
…
Linked to CU-35d7gv6, CU-35d7h2b, CU-35d7h4d
=> feat(smart-actions): add support for data-based conditions on smart action trigger, approval requirement and authorization to approve

package.json, yarn.lock
Reverts ForestAdmin/forest-express-mongoose#988
=> fix: revert "feat(smart-actions): add support for data-based conditions on smart action trigger, approval requirement and authorization to approve"

package.json, yarn.lock
=> feat(smart-actions): allow to define data-based conditions on approval requests

package.json, yarn.lock
=> fix(security): patch forest-express dependency vulnerability

package.json, yarn.lock
=> fix: revert forest-express instable dependency

package.json, yarn.lock
=> fix(security): patch forest-express dependency vulnerabilities

package.json, yarn.lock
=> fix(security): patch mongoose dev dependencies vulnerabilities

package.json, yarn.lock
=> fix(middlewares): users should be able to execute a smart action on a smart collection

package.json, yarn.lock
=> fix(init-options): liana options should be taken into account correctly

.github/workflows/build.yml, package.json, src/services/filters-parser.js, src/services/has-many-getter.js, src/services/search-builder.js, src/utils/field-analyser.js, src/utils/schema.js, test/tests/adapters/mongoose.test.js, test/tests/services/filters-parser.test.js, test/tests/services/resource-getter.test.js, test/tests/services/search-builder.test.js, test/utils/mongoose-connect.js, yarn.lock
Fixes https://github.com/ForestAdmin/forest-express-mongoose/issues/1037
=> fix(compatibility): fix mongoose 7 compatibility

package.json, yarn.lock
=> feat(events-subscription): allow to instantly refresh permissions when they change

package.json, yarn.lock
Due to https://github.com/ForestAdmin/forest-express/issues/1011
=> fix(event-source): gracefully close the app on exit by removing server events subscription

package.json, yarn.lock
=> fix(security): patch semver dependency vulnerabilities

package.json, yarn.lock
=> fix(security): patch mongoose dependency vulnerabilities

package.json, yarn.lock
=> fix: warn in the console when the schema is not updated because of NODE_ENV

package.json, yarn.lock
=> fix: warn in console when the schema is not updated because of NODE_ENV

package.json, yarn.lock
=> fix(security): patch mongodb dependency vulnerabilities

src/services/has-many-getter.js, src/services/resource-getter.js, src/services/resource-updater.js, test/tests/services/resource-getter.test.js, test/tests/services/resources-getter.test.js
=> fix(mongoose): smart has many relationships for mongoose major versions 6 and 7

package.json, yarn.lock
https://stackoverflow.com/questions/48391913/eslint-error-cannot-read-property-range-of-null
=> chore(lint): patch linter internal error

.eslintrc.js, package.json, yarn.lock
=> fix(security): patch @babel/traverse dependency vulnerabilities

package.json, yarn.lock
=> fix(serialiser):​ serialiser does not compute hidden smart fields anymore

src/services/filters-parser.js, test/tests/services/filters-parser.test.js
=> fix: allow filtering on date on smart field

package.json, yarn.lock
=> fix(security): patch express dependency vulnerabilities

package.json, yarn.lock
=> fix: typo in an error message when users are not authorized to perform an action

package.json, yarn.lock
=> fix: typo in error message

package.json, yarn.lock
=> perf: improve memory usage during export

.github/workflows/build.yml, yarn.lock
=> fix(security): patch braces dependency vulnerabilities

.github/workflows/build.yml, docker-compose.yml, yarn.lock
=> fix(security): patch micromatch dependency vulnerabilities

package.json, yarn.lock
=> feat: support action form layout description and button labels

types/index.d.ts
=> fix: submitbuttonlabel and description should be in action interface

package.json, yarn.lock
=> fix: upgrade FE to fix permission cache issue

package.json, yarn.lock
=> fix: upgrade FE to fix user perm cache issue
